imiona_meskie = (
    "Adam",
    "Bartek",
    "Cezary",
    "Dariusz",
    "Emil",
    "Filip",
    "Grzegorz",
    "Hubert",
    "Igor",
    "Jacek",
    "Kamil",
    "Łukasz",
    "Marcin",
    "Norbert",
    "Oskar",
    "Piotr",
    "Rafal",
    "Sebastian",
    "Tomasz",
    "Wojciech",
    "Zenon",
    "Adrian",
    "Bogdan",
    "Cyprian",
    "Damian",
    "Edward",
    "Franciszek",
    "Gabriel",
    "Henryk",
    "Ireneusz",
    "Jerzy",
    "Krzysztof",
    "Leszek",
    "Mariusz",
    "Nikodem",
    "Olivier",
    "Patryk",
    "Ryszard",
    "Szymon",
    "Tadeusz",
    "Waldemar",
    "Zbigniew",
    "Chris",
    "Jorge",
    "Iwan",
    "Kazimierz",
    "Kacper",
    "Bartosz",
    "Bartłomiej",
    "Alan",
    "Szymon",
    "Franciszek",
    "Miłosz",
    "Wiktor",
)

nazwiska_meskie = (
    "Kowalski",
    "Nowak",
    "Wiśniewski",
    "Dąbrowski",
    "Lewandowski",
    "Wójcik",
    "Kamiński",
    "Kowalczyk",
    "Zieliński",
    "Szymański",
    "Woźniak",
    "Kozłowski",
    "Jankowski",
    "Mazur",
    "Wojciechowski",
    "Kwiatkowski",
    "Krawczyk",
    "Kaczmarek",
    "Piotrowski",
    "Grabowski",
    "Nowicki",
    "Pawlak",
    "Michalski",
    "Wróbel",
    "Jabłoński",
    "Król",
    "Wieczorek",
    "Stępień",
    "Górski",
    "Zając",
    "Mróz",
    "Brzeziński",
    "Sikora",
    "Głowacki",
    "Krajewski",
    "Mazurek",
    "Kubiak",
    "Sadowski",
    "Borowski",
    "Baran",
    "Tomczyk",
    "Klimek",
    "Włodarczyk",
    "Bojar",
)

imiona_zenskie = (
    "Anna",
    "Barbara",
    "Celina",
    "Danuta",
    "Ewa",
    "Filipina",
    "Grażyna",
    "Halina",
    "Irena",
    "Joanna",
    "Karolina",
    "Lidia",
    "Małgorzata",
    "Natalia",
    "Olga",
    "Paulina",
    "Renata",
    "Sabina",
    "Teresa",
    "Urszula",
    "Wanda",
    "Zofia",
    "Alicja",
    "Beata",
    "Cecylia",
    "Dorota",
    "Elżbieta",
    "Franciszka",
    "Gabriela",
    "Helena",
    "Izabela",
    "Justyna",
    "Katarzyna",
    "Leokadia",
    "Maria",
    "Nina",
    "Oliwia",
    "Patrycja",
    "Renia",
    "Sylwia",
    "Teresa",
    "Weronika",
    "Zuzanna",
)

nazwiska_zenskie = (
    "Nowakowska",
    "Kowalska",
    "Wiśniewska",
    "Dąbrowska",
    "Lewandowska",
    "Wójcik",
    "Kamińska",
    "Kowalczyk",
    "Zielińska",
    "Szymańska",
    "Woźniak",
    "Kozłowska",
    "Jankowska",
    "Mazur",
    "Wojciechowska",
    "Kwiatkowska",
    "Krawczyk",
    "Kaczmarek",
    "Piotrowska",
    "Grabowska",
    "Nowicka",
    "Pawlak",
    "Michalska",
    "Wróbel",
    "Jabłońska",
    "Królowa",
    "Wieczorek",
    "Stępień",
    "Górska",
    "Zając",
    "Mróz",
    "Brzezińska",
    "Sikora",
    "Głowacka",
    "Krajewska",
    "Mazurkiewicz",
    "Kubiak",
    "Sadowska",
    "Borowska",
    "Baranowska",
    "Tomczyk",
    "Klimek",
)

kursy = (
    "Programowanie obiektowe",
    "Analiza matematyczna",
    "Algebra",
    "Fizyka",
    "Podstawy elektroniki",
    "Architektura komputerów",
    "Bazy danych",
    "Inżynieria oprogramowania",
    "Teoria sygnałów",
    "Sieci komputerowe",
    "Systemy operacyjne",
    "Matematyka dyskretna",
    "Probabilistyka",
    "Kryptografia",
    "Mechanika",
    "Elektrotechnika",
    "Mikrokontrolery",
    "Robotyka",
    "Metrologia",
    "Teoria sterowania",
    "Systemy wbudowane",
    "Teoria grafów",
    "Rachunek prawdopodobieństwa",
    "Komunikacja danych",
    "Obliczenia naukowe",
    "Wizualizacja danych",
    "Inteligencja obliczeniowa",
    "Inżynieria biomedyczna",
    "Energetyka",
    "Materiałoznawstwo",
    "Technologia informacyjna",
    "Modelowanie procesów",
    "Chemia techniczna",
    "Biocybernetyka",
    "Systemy transportowe",
    "Systemy rozproszone",
    "Grafika komputerowa",
    "Zaawansowane algorytmy",
    "Programowanie równoległe",
    "Zastosowania sztucznej inteligencji",
    "Przetwarzanie obrazów",
    "Automatyka",
    "Teoria informacji",
)
