CREATE SEQUENCE indeks
    START WITH 269999
    INCREMENT BY -1
    MINVALUE 0
    MAXVALUE 269999
    CYCLE;

CREATE SEQUENCE wydzial_id
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CYCLE;

